(in-package #:schema-protocol-arrow/tests)

(deftest emit-scalars
  (defschema %ar-user ()
    (name string)
    (age integer :optional t)
    (flag boolean)
    (score float))
  (let* ((s (emit '%ar-user))
         (fields (arrow-protocol:arrow-schema-fields s))
         (by (lambda (n)
               (find n fields :key #'arrow-protocol:arrow-field-name :test #'string=))))
    (ok (eq :utf8 (arrow-protocol:arrow-field-type (funcall by "name"))))
    (ok (eq :int64 (arrow-protocol:arrow-field-type (funcall by "age"))))
    (ok (arrow-protocol:arrow-field-nullable (funcall by "age")))
    (ok (eq :bool (arrow-protocol:arrow-field-type (funcall by "flag"))))
    (ok (eq :float64 (arrow-protocol:arrow-field-type (funcall by "score"))))
    (ok (arrow-protocol:arrow-schema-p (arrow-schema '%ar-user)))))

(deftest emit-integer-bounds
  (defschema %ar-tight ()
    (tiny (integer 0 100)))
  (let* ((s (emit '%ar-tight))
         (f (first (arrow-protocol:arrow-schema-fields s))))
    (ok (eq :int8 (arrow-protocol:arrow-field-type f)))))

(deftest emit-nested-vector
  (defschema %ar-addr ()
    (city string))
  (defschema %ar-person ()
    (home %ar-addr)
    (tags (vector string))
    (note (or :null string) :optional t))
  (let* ((s (emit '%ar-person))
         (fields (arrow-protocol:arrow-schema-fields s))
         (home (find "home" fields :key #'arrow-protocol:arrow-field-name :test #'string=))
         (tags (find "tags" fields :key #'arrow-protocol:arrow-field-name :test #'string=))
         (note (find "note" fields :key #'arrow-protocol:arrow-field-name :test #'string=)))
    (ok (eq :struct (arrow-protocol:type-head (arrow-protocol:arrow-field-type home))))
    (ok (equal '(:list :utf8) (arrow-protocol:arrow-field-type tags)))
    (ok (eq :utf8 (arrow-protocol:arrow-field-type note)))
    (ok (arrow-protocol:arrow-field-nullable note))))

(deftest emit-enum-keyword
  (defschema %ar-opt ()
    (color (member :red :blue))
    (kw keyword))
  (let* ((s (emit '%ar-opt))
         (fields (arrow-protocol:arrow-schema-fields s)))
    (ok (every (lambda (f) (eq :utf8 (arrow-protocol:arrow-field-type f))) fields))))

(deftest emit-tag-union
  (defschema %ar-ev ()
    (id string)
    (:tag kind))
  (defschema %ar-click (%ar-ev)
    (kind (eql :click) :default :click)
    (n integer))
  (defschema %ar-key (%ar-ev)
    (kind (eql :key) :default :key)
    (code string))
  (let* ((s (emit '%ar-ev))
         (fields (arrow-protocol:arrow-schema-fields s))
         (names (mapcar #'arrow-protocol:arrow-field-name fields)))
    (ok (member "id" names :test #'string=))
    (ok (member "kind" names :test #'string=))
    (ok (member "n" names :test #'string=))
    (ok (member "code" names :test #'string=))
    (ok (every #'arrow-protocol:arrow-field-nullable fields))))
