(in-package #:schema-protocol-arrow)

(defun %int-from-bounds (lo hi)
  (cond
    ((and (integerp lo) (integerp hi)
          (>= lo -128) (<= hi 127))
     :int8)
    ((and (integerp lo) (integerp hi)
          (>= lo -32768) (<= hi 32767))
     :int16)
    ((and (integerp lo) (integerp hi)
          (>= lo (- (expt 2 31))) (<= hi (1- (expt 2 31))))
     :int32)
    (t :int64)))

(defun %or-null-inner (spec)
  "If SPEC is (or :null T) / (or T :null), return (values T nullable). Else (values SPEC nil)."
  (if (eq (type-kind spec) :or)
      (let ((args (type-args spec)))
        (cond
          ((and (= 2 (length args))
                (or (eq (type-kind (first args)) :null)
                    (eq (first args) :null)))
           (values (second args) t))
          ((and (= 2 (length args))
                (or (eq (type-kind (second args)) :null)
                    (eq (second args) :null)))
           (values (first args) t))
          (t (values spec nil))))
      (values spec nil)))

(defun type-arrow-type (spec slot)
  (multiple-value-bind (inner nullable) (%or-null-inner spec)
    (declare (ignore nullable))
    (let ((kind (type-kind inner)))
      (case kind
        (:null :null)
        (:string :utf8)
        (:boolean :bool)
        ((:float :real :number) :float64)
        (:integer
         (let ((args (type-args inner)))
           (%int-from-bounds (or (and slot (slot-minimum slot)) (first args))
                             (or (and slot (slot-maximum slot)) (second args)))))
        ((:keyword :symbol :member :enum :eql) :utf8)
        ((:vector :list :sequence)
         (list :list (type-arrow-type (or (sequence-element-type inner slot) 'string) nil)))
        (:nested
         (cons :struct (schema-fields (find-schema inner))))
        (:or :utf8)
        ((:hash-table :any :lisp :satisfies) :utf8)
        (t :utf8)))))

(defun schema-fields (class)
  (finalize-schema class)
  (when (and (schema-tag class) (schema-variants class))
    (return-from schema-fields (%tagged-fields class)))
  (let ((fields '()))
    (dolist (slot (schema-slots class))
      (when (and (slot-wire-p slot) (slot-dump-p slot))
        (multiple-value-bind (inner nullable-or) (%or-null-inner (slot-definition-type slot))
          (declare (ignore inner))
          (push (make-arrow-field
                 :name (slot-wire-key slot class)
                 :type (type-arrow-type (slot-definition-type slot) slot)
                 :nullable (or nullable-or
                               (slot-optional-p slot)
                               (not (slot-is-required-p slot))))
                fields))))
    (nreverse fields)))

(defun %tagged-fields (class)
  (let ((seen (make-hash-table :test #'equal))
        (fields '()))
    (labels ((add (slot owner)
               (let ((key (slot-wire-key slot owner)))
                 (unless (gethash key seen)
                   (setf (gethash key seen) t)
                   (push (make-arrow-field
                          :name key
                          :type (type-arrow-type (slot-definition-type slot) slot)
                          :nullable t)
                         fields)))))
      (dolist (slot (schema-slots class))
        (when (and (slot-wire-p slot) (slot-dump-p slot))
          (add slot class)))
      (dolist (v (schema-variants class))
        (finalize-schema v)
        (dolist (slot (schema-slots v))
          (when (and (slot-wire-p slot) (slot-dump-p slot))
            (add slot v)))))
    (nreverse fields)))

(defun emit (schema)
  "defschema / schema-class / instance → arrow-protocol:arrow-schema."
  (make-arrow-schema (schema-fields (schema-of schema))))
